#ifndef __SETTINGS_H
#define __SETTINGS_H

#define LIGHT_SENSOR_LOWER_THRESHOLD 1500
#define LIGHT_SENSOR_UPPER_THRESHOLD 1900


// #define HEART_BEAT_TIME 1000
//#define LIGHT_SENSOR_UPPER_THRESHOLD 1900


#endif
